### ISSUE TITLE
Q: Selection of static type checker

### ISSUE THREAD

**Issue by bm-stschneider** [github/details-dialog-element#20]
I think this is a good example of custom element composition. I was just wondering, why was flow chosen over typescript for example?

**Comment by muan** [comment]
Flow was chosen here because of github.com JS uses Flow. And that decision was made 2 years ago when it was way easier to use Flow with Babel than TypeScript with Babel. Now with Babel 7 we might reevaluate, but there's no timeline to switch at this point.
