### ISSUE TITLE
Post-close event to manage focus 

### ISSUE THREAD

**Issue by feministy** [github/details-dialog-element#24]
Hello friends 👋 

I am working in a system that uses websockets to process live updates and replace chunks of the DOM. In order for this live update to be successful, the element being replaced cannot have any interactions. 

Because `details-dialog` is managing focus after it is closed, I get stuck in this workflow with an `activeElement`:

1. Click "Close" button
2. `details-dialog` opens and user confirms the behavior is desired by clicking another "Close" button
3. Form is submitted
4. `details-dialog` closes
5. Live update fails to replace the "Close" button from step 1 fails because `details-dialog` has called `focus()` on that button

Normally I would call `blur()` here, but we are removing `blur()` from the code base where possible to improve accessibility.

🌮 ty for your help!!

**Comment by muan** [comment]
I believe we can now address this issue in live update. See https://github.com/github/github/pull/127656 (and might have already been fixed in https://github.com/github/github/commit/17ff11e6351899fb0832d32bfc475eeaab7de445).
