### ISSUE TITLE
"You can click anywhere to dismiss without JS" is not anywhere

### ISSUE THREAD

**Issue by AdrianoCahete** [github/details-dialog-element#25]
Just a follow up that, in the demo for Bare, shows up a message saying "But you can click anywhere to dismiss without JS.".

In fact, if you click on this text, isn't dismissed. 😋

**Comment by philg-ygt** [comment]
Having some border around the dialog and updating the text to be "You can click anywhere outside the dialog to dismiss without JS" would do.
