### ISSUE TITLE
INPUT_SELECTOR limits use of custom buttons

### ISSUE THREAD

**Issue by bennypowers** [github/details-dialog-element#26]
Consider:

```html
<details id="update-dialog" hidden>
  <summary>New Version</summary>
  <details-dialog>
    <h1>New Version Available!</h1>
    <p>Reload the Page?</p>
    <mwc-button id="dialog-reload">OK</mwc-button>
    <mwc-button data-close-dialog>Cancel</mwc-button>
  </details-dialog>
</details>
```

This will fail entirely, since the requisite inputs are not found when the element boots up.

By adding `mwc-button` to the `INPUT_SELECTOR`, expected behaviour is restored.

I recommend adding a special attribute to the list, like so:

```html
<details id="update-dialog" hidden>
  <summary>New Version</summary>
  <details-dialog>
    <h1>New Version Available!</h1>
    <p>Reload the Page?</p>
    <mwc-button data-dialog-input id="dialog-reload">OK</mwc-button>
    <mwc-button data-dialog-input data-close-dialog>Cancel</mwc-button>
  </details-dialog>
</details>
```

**Comment by muan** [comment]
Hi! Thanks for the issue. Just to give you an update- we are looking into this and want to come up with a solution that can best ensure these elements are indeed focusable to guard against human errors. We are going to look into how we might be able to work better with `delegateFocus` shadow roots (in `<mwc-button>`'s case).
