### ISSUE TITLE
Add example for usage in React application

### ISSUE THREAD

**Issue by abatilo** [github/details-dialog-element#51]
It would be nice to see an example for how to utilize this library from within a TypeScript React application. How do you import a custom component like this?

**Comment by koddsson** [comment]
Hey @abatilo 👋

I think starting off with the [official react documentation](https://reactjs.org/docs/web-components.html) might be good. As far as I know, you don't need to do anything special to import a web component in a react app.

**Comment by abatilo** [comment]
Thanks @koddsson! I'm fairly familiar with React. You're right about not needing anything for a JavaScript react app, but the type definitions in this project are incomplete. There were two things that were giving me trouble, but I got myself unblocked. For anyone else that ends up having trouble here:

1. Add type declaration to your project: https://wespeter.com/posts/consuming-web-component-react-typescript/
2. I was trying to use the `Box--overlay` classes here: https://primer.style/css/components/box-overlay

The `Box--overlay` css is not a part of the primer library, so no styles were getting applied.

I ended up ignoring the `Box--overlay` and including the following style in my scss:
https://github.com/github/details-dialog-element/blob/master/index.css

Closing this issue now. Thanks again.

**Comment by koddsson** [comment]
> but the type definitions in this project are incomplete.

Could you explain this further. As far as I know we got TypeScript and Flow files that describe the element API and those should be picked up by a consuming app when the component is imported.
