### ISSUE TITLE
Open a dialog from JavaScript

### ISSUE THREAD

**Issue by vmsp** [github/details-dialog-element#55]
I.e. kindly make [dialog()](https://github.github.io/web-systems-documentation/#modules-dialog-md) from the internal GitHub repository public.

Thank you, this element is awesome!

**Comment by koddsson** [comment]
Hey @vmsp. The `dialog()` function just clones the template element that is passed to it, does some assertions on the DOM  +  some other GitHub specific stuff so I don't think there would be any value in open sourcing it.

Is there anything specific that you are looking for?
